name: Deploy to Google Cloud

on:
        push:
                branches:
                        - main # Este workflow será executado sempre que houver um push para o branch 'main'

env:
  PROJECT_ID: project-b592c6c5-e1fe-4aeb-b37
  WIP_POOL_ID: gian-personal-github-pool
  WIP_PROVIDER_ID: github
  SERVICE_ACCOUNT_EMAIL: github-actions-db-access@project-b592c6c5-e1fe-4aeb-b37.iam.gserviceaccount.com

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ env.WIP_POOL_ID }}/providers/${{ env.WIP_PROVIDER_ID }}'
        service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Apenas um passo de teste
      run: echo "Hello, GitHub Actions!"
